#!/bin/sh
read -r -d '' copyqjs << EOM
for (var i = 0; i < size(); i++) {
  var lines = str(read(i)).split(/[\r\n]+/);
  var line = "";

  if (lines.length > 1) {
    line = lines[0] + " (+" + str(lines.length - 1) + " more lines)";
  } else {
    line = lines[0];
  }

  if (line == "") {
      line = '<probably image>';
  }

  print(i + " " + line + "\n");
}
EOM

pick="$(echo "$copyqjs" | copyq eval - | dmenu -i -l 20 -m 1 -fn 'monospace:size=14' -nb '#222222' -nf '#bbbbbb' -sb '#bf616a' -sf '#3b4252' | awk '{print $1}')"

if [[ "$pick" != "" ]]; then
    copyq select "$pick"
fi
